### ISSUE TITLE
Cannot run the project: Could not determine java version from '9.0.4'.

### ISSUE THREAD

**Issue by eriknyk** [ssouris/spring5-reactive-sample#3]
Hi, I cannot run the project I'm getting the following error message from jIdea:

Could not determine java version from '9.0.4'.

however I'm running java 9.0.4

```
erik@localhost:~$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

Any help will be appreciated.

**Comment by eriknyk** [comment]
going back to java 1.8 solved it

**Comment by ssouris** [comment]
Yeah this was not buily with Java 9 in mind.
